/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2018 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (__fastcall *__fastcall sub_A79(__int64 a1, __int64 a2, __int64 (__fastcall *a3)(char *), __int64 (__fastcall *a4)(__int64, char *), __int64 a5))(__int64, __int64 (__fastcall *)());
__int64 __fastcall sub_2322(__int64 a1);
void *sub_2A16();


//----- (0000000000000A79) ----------------------------------------------------
__int64 (__fastcall *__fastcall sub_A79(__int64 a1, __int64 a2, __int64 (__fastcall *a3)(char *), __int64 (__fastcall *a4)(__int64, char *), __int64 a5))(__int64, __int64 (__fastcall *)())
{
  __int64 (__fastcall *result)(__int64, __int64 (__fastcall *)()); // rax
  __int64 v6; // rax
  __int64 NtQueryVirtualMemory; // rax
  int mm; // [rsp+30h] [rbp-3E8h]
  char v9; // [rsp+34h] [rbp-3E4h]
  int i; // [rsp+38h] [rbp-3E0h]
  char v11; // [rsp+3Ch] [rbp-3DCh]
  int l; // [rsp+40h] [rbp-3D8h]
  int j; // [rsp+44h] [rbp-3D4h]
  int n; // [rsp+48h] [rbp-3D0h]
  int jj; // [rsp+4Ch] [rbp-3CCh]
  int ll; // [rsp+50h] [rbp-3C8h]
  int k; // [rsp+54h] [rbp-3C4h]
  int m; // [rsp+58h] [rbp-3C0h]
  int ii; // [rsp+5Ch] [rbp-3BCh]
  int kk; // [rsp+60h] [rbp-3B8h]
  char v21; // [rsp+68h] [rbp-3B0h]
  char v22; // [rsp+76h] [rbp-3A2h]
  char v23; // [rsp+78h] [rbp-3A0h]
  char v24; // [rsp+80h] [rbp-398h]
  char v25; // [rsp+88h] [rbp-390h]
  char v26; // [rsp+89h] [rbp-38Fh]
  char v27; // [rsp+8Ah] [rbp-38Eh]
  char v28; // [rsp+8Bh] [rbp-38Dh]
  char v29; // [rsp+8Ch] [rbp-38Ch]
  char v30; // [rsp+8Dh] [rbp-38Bh]
  char v31; // [rsp+8Eh] [rbp-38Ah]
  char v32; // [rsp+90h] [rbp-388h]
  char v33; // [rsp+91h] [rbp-387h]
  char v34; // [rsp+92h] [rbp-386h]
  char v35; // [rsp+93h] [rbp-385h]
  char v36; // [rsp+94h] [rbp-384h]
  char v37; // [rsp+95h] [rbp-383h]
  char v38; // [rsp+96h] [rbp-382h]
  char v39; // [rsp+98h] [rbp-380h]
  char v40; // [rsp+A8h] [rbp-370h]
  char v41; // [rsp+B8h] [rbp-360h]
  char v42; // [rsp+B9h] [rbp-35Fh]
  char v43; // [rsp+BAh] [rbp-35Eh]
  char v44; // [rsp+BBh] [rbp-35Dh]
  char v45; // [rsp+BCh] [rbp-35Ch]
  char v46; // [rsp+BDh] [rbp-35Bh]
  char v47; // [rsp+BEh] [rbp-35Ah]
  char v48; // [rsp+BFh] [rbp-359h]
  char v49; // [rsp+C0h] [rbp-358h]
  char v50; // [rsp+C1h] [rbp-357h]
  char v51; // [rsp+C8h] [rbp-350h]
  char v52; // [rsp+D8h] [rbp-340h]
  char v53; // [rsp+E8h] [rbp-330h]
  char v54; // [rsp+F8h] [rbp-320h]
  char v55; // [rsp+108h] [rbp-310h]
  char v56; // [rsp+118h] [rbp-300h]
  char v57; // [rsp+128h] [rbp-2F0h]
  char v58; // [rsp+138h] [rbp-2E0h]
  char v59; // [rsp+148h] [rbp-2D0h]
  char v60; // [rsp+158h] [rbp-2C0h]
  char v61; // [rsp+170h] [rbp-2A8h]
  char v62; // [rsp+188h] [rbp-290h]
  char v63; // [rsp+1A0h] [rbp-278h]
  char v64; // [rsp+1B8h] [rbp-260h]
  char v65; // [rsp+1D0h] [rbp-248h]
  char v66; // [rsp+1E8h] [rbp-230h]
  char v67; // [rsp+200h] [rbp-218h]
  char v68; // [rsp+201h] [rbp-217h]
  char v69; // [rsp+202h] [rbp-216h]
  char v70; // [rsp+203h] [rbp-215h]
  char v71; // [rsp+204h] [rbp-214h]
  char v72; // [rsp+205h] [rbp-213h]
  char v73; // [rsp+206h] [rbp-212h]
  char v74; // [rsp+207h] [rbp-211h]
  char v75; // [rsp+208h] [rbp-210h]
  char v76; // [rsp+209h] [rbp-20Fh]
  char v77; // [rsp+20Ah] [rbp-20Eh]
  char v78; // [rsp+20Bh] [rbp-20Dh]
  char v79; // [rsp+20Ch] [rbp-20Ch]
  char v80; // [rsp+20Dh] [rbp-20Bh]
  char v81; // [rsp+20Eh] [rbp-20Ah]
  char v82; // [rsp+20Fh] [rbp-209h]
  char v83; // [rsp+210h] [rbp-208h]
  char v84; // [rsp+211h] [rbp-207h]
  char v85; // [rsp+212h] [rbp-206h]
  char v86; // [rsp+213h] [rbp-205h]
  char v87; // [rsp+214h] [rbp-204h]
  char v88; // [rsp+215h] [rbp-203h]
  char v89; // [rsp+216h] [rbp-202h]
  char v90; // [rsp+217h] [rbp-201h]
  char v91; // [rsp+218h] [rbp-200h]
  char v92; // [rsp+220h] [rbp-1F8h]
  char v93; // [rsp+240h] [rbp-1D8h]
  char v94; // [rsp+260h] [rbp-1B8h]
  int nn; // [rsp+280h] [rbp-198h]
  __int64 (__fastcall *v96)(__int64); // [rsp+288h] [rbp-190h]
  __int64 hNtdll; // [rsp+290h] [rbp-188h]
  int v98; // [rsp+298h] [rbp-180h]
  unsigned int v99; // [rsp+29Ch] [rbp-17Ch]
  __int64 v100; // [rsp+2A0h] [rbp-178h]
  __int64 v101; // [rsp+2A8h] [rbp-170h]
  __int64 v102; // [rsp+2B0h] [rbp-168h]
  __int64 v103; // [rsp+2B8h] [rbp-160h]
  __int64 v104; // [rsp+2C0h] [rbp-158h]
  void (__fastcall *Sleep)(__int64); // [rsp+2C8h] [rbp-150h]
  __int64 v106; // [rsp+2D0h] [rbp-148h]
  __int64 v107; // [rsp+2D8h] [rbp-140h]
  __int64 v108; // [rsp+2E0h] [rbp-138h]
  char *v109; // [rsp+2E8h] [rbp-130h]
  __int64 v110; // [rsp+2F0h] [rbp-128h]
  __int64 v111; // [rsp+2F8h] [rbp-120h]
  __int64 v112; // [rsp+300h] [rbp-118h]
  __int64 v113; // [rsp+308h] [rbp-110h]
  __int64 v114; // [rsp+310h] [rbp-108h]
  __int64 v115; // [rsp+318h] [rbp-100h]
  __int64 (__fastcall *AddVectoredExceptionHandler)(__int64, __int64 (__fastcall *)()); // [rsp+320h] [rbp-F8h]
  __int64 v117; // [rsp+328h] [rbp-F0h]
  __int64 (__fastcall *v118)(__int64, __int64 (__fastcall *)()); // [rsp+330h] [rbp-E8h]
  int (__fastcall *NtProtectVirtualMemory)(__int64, __int64 *, __int64 *, __int64, unsigned int *); // [rsp+338h] [rbp-E0h]
  __int64 v120; // [rsp+340h] [rbp-D8h]
  void (__fastcall *RemoveVectoredExceptionHandler)(__int64 (__fastcall *)(__int64, __int64 (__fastcall *)())); // [rsp+348h] [rbp-D0h]
  __int64 v122; // [rsp+350h] [rbp-C8h]
  __int64 GetAsyncKeyState; // [rsp+360h] [rbp-B8h]
  __int64 v124; // [rsp+360h] [rbp-B8h] FORCED
  __int64 v125; // [rsp+368h] [rbp-B0h]
  _DWORD *IsBadReadPtr; // [rsp+370h] [rbp-A8h]
  __int64 v127; // [rsp+378h] [rbp-A0h]
  __int64 v128; // [rsp+380h] [rbp-98h]
  __int64 v129; // [rsp+388h] [rbp-90h]
  __int64 v130; // [rsp+390h] [rbp-88h]
  __int64 v131; // [rsp+398h] [rbp-80h]
  __int64 v132; // [rsp+3A0h] [rbp-78h]
  _DWORD *v133; // [rsp+3C0h] [rbp-58h]
  __int64 v134; // [rsp+3C8h] [rbp-50h]
  __int64 v135; // [rsp+3D0h] [rbp-48h]
  __int64 v136; // [rsp+3D8h] [rbp-40h]
  __int64 v137; // [rsp+3E0h] [rbp-38h]
  __int64 v138; // [rsp+3F0h] [rbp-28h]
  __int64 v139; // [rsp+3F8h] [rbp-20h]
  __int64 v140; // [rsp+400h] [rbp-18h]
  __int64 v141; // [rsp+428h] [rbp+10h]
  __int64 (__fastcall *GetModuleHandle)(char *); // [rsp+430h] [rbp+18h]
  __int64 (__fastcall *GetProcAddress)(__int64, char *); // [rsp+438h] [rbp+20h]

  GetProcAddress = a4;
  GetModuleHandle = a3;
  v141 = a2;
  strcpy(&v58, "KERNEL32.dll");
  v106 = a3(&v58);
  v11 = 1;
  strcpy(&v61, "BEClient_x64.dll");
  v114 = GetModuleHandle(&v61);
  if ( *(_DWORD *)(v114 + *(int *)(v114 + 60) + 8) < 0x5D7AA2AFu )
    v109 = &v11;
  else
    v109 = (char *)a5;
  strcpy(&v93, "AddVectoredExceptionHandler");
  result = (__int64 (__fastcall *)(__int64, __int64 (__fastcall *)()))GetProcAddress(v106, &v93);
  AddVectoredExceptionHandler = result;
  if ( result )
  {
    v96 = sub_2322;
    *(_QWORD *)((char *)sub_2322 + 14) = v141;
    strcpy(&v40, "ntdll.dll");
    v6 = GetModuleHandle(&v40);
    hNtdll = v6;
    strcpy(&v64, "NtQueryVirtualMemory");
    NtQueryVirtualMemory = GetProcAddress(v6, &v64);
    v122 = NtQueryVirtualMemory;
    *(_QWORD *)((char *)v96 + 29) = NtQueryVirtualMemory;
    *(_QWORD *)((char *)v96 + 47) = GetModuleHandle(0i64);
    result = (__int64 (__fastcall *)(__int64, __int64 (__fastcall *)()))AddVectoredExceptionHandler(
                                                                          1i64,
                                                                          (__int64 (__fastcall *)())v96);
    v118 = result;
    if ( result )
    {
      memset(&GetAsyncKeyState, 0, 0xB0ui64);
      strcpy(&v54, "USER32.dll");
      v100 = GetModuleHandle(&v54);
      strcpy(&v60, "GetAsyncKeyState");
      v124 = GetProcAddress(v100, &v60);
      strcpy(&v57, "GetCursorPos");
      v125 = GetProcAddress(v100, &v57);
      strcpy(&v56, "IsBadReadPtr");
      IsBadReadPtr = (_DWORD *)GetProcAddress(v106, &v56);
      strcpy(&v53, "win32u.dll");
      v117 = GetModuleHandle(&v53);
      strcpy(&v66, "NtUserGetAsyncKeyState");
      v127 = GetProcAddress(v117, &v66);
      strcpy(&v63, "GetForegroundWindow");
      v128 = GetProcAddress(v100, &v63);
      strcpy(&v21, "CallWindowProcW");
      v129 = GetProcAddress(v100, &v21);
      strcpy(&v62, "NtUserPeekMessage");
      v130 = GetProcAddress(v117, &v62);
      strcpy(&v52, "NtSetEvent");
      v131 = GetProcAddress(hNtdll, &v52);
      for ( i = 6; i <= 7; ++i )
      {
        if ( *(&v124 + i) )
        {
          for ( j = 0; j < 32; ++j )
          {
            _mm_lfence();
            if ( *(_WORD *)(*(&v124 + i) + j) == 1295 )
            {
              _mm_lfence();
              if ( *(unsigned __int8 *)(*(&v124 + i) + j + 2) == 195 )
              {
                *(&v124 + i) += j;
                break;
              }
            }
          }
        }
      }
      strcpy(&v59, "UnityPlayer.dll");
      v104 = GetModuleHandle(&v59);
      *(_QWORD *)((char *)v96 + 0x2F) = v104;
      if ( *(_DWORD *)(v104 + 0x55B942) == 0xC35B5D5F && *(_DWORD *)(v104 + 0x54B6CB) == 0x48038B48 )
        v132 = v104 + 0x55B945;
      if ( IsBadReadPtr && *IsBadReadPtr == 0x18EC8348 )
        v133 = IsBadReadPtr + 1;
      v67 = 0x48;
      v68 = 0x89u;
      v69 = 0x45;
      v70 = 0x58;
      v71 = 0x48;
      v72 = 0x8Bu;
      v73 = 0xCDu;
      v74 = 0x48;
      v75 = 0x8Bu;
      v76 = 0x43;
      v77 = 0x58;
      v78 = 0x48;
      v79 = 0x89u;
      v80 = 0x45;
      v81 = 0x60;
      v82 = 0x48;
      v83 = 0x8Bu;
      v84 = 0x53;
      v85 = 0x58;
      v86 = 0x48;
      v87 = 0x8Bu;
      v88 = 0x43;
      v89 = 0x50;
      v90 = 0xFFu;
      v91 = 0x15;
      v115 = hNtdll + *(int *)(hNtdll + 0x3C) + 0x18;
      v110 = *(unsigned int *)(v115 + 0x14) + hNtdll;
      for ( k = 0; k + 25i64 <= (unsigned __int64)*(unsigned int *)(v115 + 4); ++k )
      {
        for ( l = 0; (unsigned __int64)l < 25 && *(unsigned __int8 *)(v110 + l + k) == (unsigned __int8)*(&v67 + l); ++l )
          ;
        if ( l == 25i64 )
        {
          v134 = k + v110 + l - 2;
          break;
        }
      }
      strcpy(&v55, "ucrtbase.dll");
      v107 = GetModuleHandle(&v55);
      if ( v107 )
      {
        strcpy(&v23, "sqrtf");
        v135 = GetProcAddress(v107, &v23);
        strcpy(&v92, "__stdio_common_vsprintf_s");
        v136 = GetProcAddress(v107, &v92);
      }
      strcpy(&v39, "dxgi.dll");
      v103 = GetModuleHandle(&v39);
      if ( v103 )
      {
        v25 = 72;
        v26 = -125;
        v27 = -63;
        v28 = -128;
        v29 = 72;
        v30 = -1;
        v31 = 37;
        v111 = v103 + *(int *)(v103 + 60) + 24;
        v112 = *(unsigned int *)(v111 + 20) + v103;
        for ( m = 0; m + 7i64 <= (unsigned __int64)*(unsigned int *)(v111 + 4); ++m )
        {
          for ( n = 0; (unsigned __int64)n < 7 && *(unsigned __int8 *)(v112 + n + m) == (unsigned __int8)*(&v25 + n); ++n )
            ;
          if ( n == 7i64 )
          {
            v137 = m + v112;
            break;
          }
        }
      }
      v22 = 65;
      v138 = GetProcAddress(v100, &v21);
      strcpy(&v51, "d3d11.dll");
      v102 = GetModuleHandle(&v51);
      if ( v102 )
      {
        v41 = 0;
        v42 = 0;
        v43 = 0x45;
        v44 = 0x33;
        v45 = 0xC9u;
        v46 = 0x44;
        v47 = 0x3B;
        v48 = 0xD0u;
        v49 = 0x77;
        v50 = 8;
        v108 = v102 + *(int *)(v102 + 60) + 24;
        v101 = *(unsigned int *)(v108 + 20) + v102;
        for ( ii = 0; ii + 10i64 <= (unsigned __int64)*(unsigned int *)(v108 + 4); ++ii )
        {
          for ( jj = 0;
                (unsigned __int64)jj < 0xA && *(unsigned __int8 *)(v101 + jj + ii) == (unsigned __int8)*(&v41 + jj);
                ++jj )
          {
            ;
          }
          if ( jj == 10i64 )
          {
            v139 = v101 + ii - 19;
            break;
          }
        }
        v32 = 0x48;
        v33 = 0x83u;
        v34 = 0xC1u;
        v35 = 0x10;
        v36 = 0x48;
        v37 = 0xFFu;
        v38 = 0x25;
        for ( kk = 0; kk + 7i64 <= (unsigned __int64)*(unsigned int *)(v108 + 4); ++kk )
        {
          for ( ll = 0;
                (unsigned __int64)ll < 7 && *(unsigned __int8 *)(v101 + ll + kk) == (unsigned __int8)*(&v32 + ll);
                ++ll )
          {
            ;
          }
          if ( ll == 7i64 )
          {
            v140 = kk + v101;
            break;
          }
        }
      }
      strcpy(&v24, "Sleep");
      Sleep = (void (__fastcall *)(__int64))GetProcAddress(v106, &v24);
      strcpy(&v65, "NtProtectVirtualMemory");
      NtProtectVirtualMemory = (int (__fastcall *)(__int64, __int64 *, __int64 *, __int64, unsigned int *))GetProcAddress(hNtdll, &v65);
      for ( mm = 0; *v109 && (unsigned __int64)mm < 0x16; ++mm )
      {
        if ( *(&v124 + mm) )
        {
          v113 = 1i64;
          v120 = *(&v124 + mm);
          if ( NtProtectVirtualMemory(-1i64, &v120, &v113, 64i64, &v99) >= 0 )
          {
            *((_BYTE *)v96 + 64) = mm;
            v9 = *(_BYTE *)*(&v124 + mm);
            *((_BYTE *)v96 + 69) = v9;
            *(_BYTE *)*(&v124 + mm) = -52;
            if ( mm != 6 && mm != 7 && mm != 8 )
            {
              for ( nn = 0; *v109; ++nn )
              {
                v98 = mm == 19 ? 400 : 200;
                if ( nn >= v98 )
                  break;
                Sleep(5i64);
                if ( *(unsigned __int8 *)*(&v124 + mm) != 0xCC )
                  *(_BYTE *)*(&v124 + mm) = 0xCCu;
              }
            }
            else
            {
              Sleep(1000i64);
            }
            *(_BYTE *)*(&v124 + mm) = v9;
            Sleep(1000i64);
            NtProtectVirtualMemory(-1i64, &v120, &v113, v99, &v99);
          }
        }
      }
      strcpy(&v94, "RemoveVectoredExceptionHandler");
      RemoveVectoredExceptionHandler = (void (__fastcall *)(__int64 (__fastcall *)(__int64, __int64 (__fastcall *)())))GetProcAddress(v106, &v94);
      RemoveVectoredExceptionHandler(v118);
      result = (__int64 (__fastcall *)(__int64, __int64 (__fastcall *)()))((__int64 (__fastcall *)(__int64))Sleep)(100i64);
    }
  }
  return result;
}

//----- (0000000000002322) ----------------------------------------------------
__int64 __fastcall sub_2322(__int64 a1)
{
  __int64 result; // rax
  __int64 *v2; // [rsp+38h] [rbp-190h]
  bool v3; // [rsp+44h] [rbp-184h]
  int v4; // [rsp+48h] [rbp-180h]
  int v5; // [rsp+4Ch] [rbp-17Ch]
  _BYTE *v6; // [rsp+60h] [rbp-168h]
  __int64 v7; // [rsp+68h] [rbp-160h]
  __int64 v8; // [rsp+70h] [rbp-158h]
  char v9; // [rsp+80h] [rbp-148h]
  char v10; // [rsp+81h] [rbp-147h]
  char v11; // [rsp+82h] [rbp-146h]
  __int64 *v12; // [rsp+83h] [rbp-145h]
  __int64 v13; // [rsp+8Bh] [rbp-13Dh]
  __int64 v14; // [rsp+93h] [rbp-135h]
  __int64 v15; // [rsp+9Bh] [rbp-12Dh]
  __int64 v16; // [rsp+A3h] [rbp-125h]
  __int64 v17; // [rsp+ABh] [rbp-11Dh]
  __int64 v18; // [rsp+B3h] [rbp-115h]
  int v19; // [rsp+BBh] [rbp-10Dh]
  int v20; // [rsp+BFh] [rbp-109h]
  char v21; // [rsp+D0h] [rbp-F8h]
  char v22; // [rsp+D1h] [rbp-F7h]
  char v23; // [rsp+D2h] [rbp-F6h]
  __int64 *v24; // [rsp+D3h] [rbp-F5h]
  __int64 v25; // [rsp+DBh] [rbp-EDh]
  __int64 v26; // [rsp+E3h] [rbp-E5h]
  __int64 v27; // [rsp+EBh] [rbp-DDh]
  __int64 v28; // [rsp+F3h] [rbp-D5h]
  __int64 v29; // [rsp+FBh] [rbp-CDh]
  __int64 v30; // [rsp+103h] [rbp-C5h]
  int v31; // [rsp+10Bh] [rbp-BDh]
  int v32; // [rsp+10Fh] [rbp-B9h]
  __int64 v33; // [rsp+120h] [rbp-A8h]
  __int64 v34; // [rsp+128h] [rbp-A0h]
  __int64 v35; // [rsp+130h] [rbp-98h]
  unsigned __int64 v36; // [rsp+140h] [rbp-88h]
  int v37; // [rsp+148h] [rbp-80h]
  int v38; // [rsp+14Ch] [rbp-7Ch]
  int v39; // [rsp+150h] [rbp-78h]
  __int64 v40; // [rsp+1B0h] [rbp-18h]
  char v41; // [rsp+1B8h] [rbp-10h]
  __int64 v42; // [rsp+1D0h] [rbp+8h]

  v42 = a1;
  v33 = 140723368084672i64;
  if ( **(_DWORD **)a1 == -2147483645 )
  {
    **(_BYTE **)(*(_QWORD *)(a1 + 8) + 248i64) = 68;
    v40 = MEMORY[0x7FFC8964003C] + 140722613518360i64;
    v6 = (char *)sub_2A16() + 3;
    if ( *v6 )
    {
      v2 = **(__int64 ***)(*(_QWORD *)(v42 + 8) + 152i64);
      v3 = ((int (__fastcall *)(__int64, __int64 *, _QWORD, __int64 *, __int64, char *))v33)(
             -1i64,
             v2,
             0i64,
             &v34,
             48i64,
             &v41) < 0;
      if ( v3
        || v37 != 4096
        || v39 != 0x1000000 && v36 > 0x2000
        || *(_WORD *)v2 == 9215
        || *(_WORD *)v2 == 9983
        || *(_WORD *)v2 == 10239
        || *(_WORD *)v2 == 26111
        || *(unsigned __int16 *)v2 == 58367
        || *(unsigned __int16 *)v2 == 65345 )
      {
        *v6 = 11;
        v9 = 0;
        v10 = 49;
        v11 = 51;
        v12 = v2;
        v13 = *v2;
        v14 = v2[1];
        v15 = v2[2];
        v16 = v2[3];
        if ( v3 )
          v7 = 0i64;
        else
          v7 = v35;
        v17 = v7;
        if ( v3 )
          v8 = 0i64;
        else
          v8 = v34;
        v18 = v8;
        if ( v3 )
          v4 = 0;
        else
          v4 = v36;
        v19 = v4;
        if ( v3 )
          v5 = 0;
        else
          v5 = v39 | v38 | v37;
        v20 = v5;
        MEMORY[0x7FFC8521BDE0](&v9, 67i64, 0i64);
      }
    }
    result = 0xFFFFFFFFi64;
  }
  else if ( **(_DWORD **)a1 == -2147483644 )
  {
    if ( *(_QWORD *)(*(_QWORD *)(a1 + 8) + 248i64) >= 0x8000000000000000ui64 )
    {
      v21 = 0;
      v22 = 49;
      v23 = 51;
      v24 = *(__int64 **)(*(_QWORD *)(a1 + 8) + 248i64);
      v25 = *v24;
      v26 = v24[1];
      v27 = v24[2];
      v28 = v24[3];
      v29 = 0i64;
      v30 = 0i64;
      v31 = 0;
      v32 = 0;
      MEMORY[0x7FFC8521BDE0](&v21, 67i64, 0i64);
    }
    result = 0xFFFFFFFFi64;
  }
  else
  {
    result = 0i64;
  }
  return result;
}

//----- (0000000000002A16) ----------------------------------------------------
void *sub_2A16()
{
  void *retaddr; // [rsp+0h] [rbp+0h]

  return retaddr;
}

// ALL OK, 3 function(s) have been successfully decompiled
